#pragma once

#pragma OPENCL EXTENSION cl_khr_fp16 : enable

#define WARP_SIZE 32
#ifndef TOTAL_WARPS
#define TOTAL_WARPS 16
#endif

#define B60_SLM_SIZE_PER_XEHP_IN_BYTES 128 * 1024
#define B60_HW_THREADS_PER_XEHP 64
#define SINGLE_WORKER_B60_MAX_SLM_SIZE_IN_BYTES \
  B60_SLM_SIZE_PER_XEHP_IN_BYTES / (B60_HW_THREADS_PER_XEHP / TOTAL_WARPS)