name: Automate Issue Assignment in the GFI board

on:
  issues:
    types: [assigned, unassigned]

jobs:
  issue_assigned:
    if: github.event.action == 'assigned'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Good first issues
          column: Assigned
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  
  issue_assigned:
    if: github.event.action == 'unassigned'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Good first issues
          column: Contributors needed
          repo-token: ${{ secrets.GITHUB_TOKEN }}
