name: megakernel-ci-test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    container:
      image: pk_dev_image:latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          path: ./repo
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          test -f /.dockerenv && echo "RUNNING INSIDE DOCKER"
          ls ./repo
      - run: echo "📂 The current working directory is ./repo ."
      - run: echo "📝 The contents of the current working directory are:"
      - run: ls -la ./repo
      - run: echo "🍏 This job's status is ${{ job.status }}."
